# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Raft.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'Raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nRaft.proto\"&\n\x12SetIsActiveRequest\x12\x10\n\x08isActive\x18\x01 \x01(\x08\"\'\n\x13SetIsActiveResponse\x12\x10\n\x08isActive\x18\x01 \x01(\x08\"&\n\x12GetIsActiveRequest\x12\x10\n\x08isActive\x18\x01 \x01(\x08\"\'\n\x13GetIsActiveResponse\x12\x10\n\x08isActive\x18\x01 \x01(\x08\"\x1b\n\x0bStopRequest\x12\x0c\n\x04stop\x18\x01 \x01(\x08\"\x1f\n\x0cStopResponse\x12\x0f\n\x07stopped\x18\x01 \x01(\x08\"\x10\n\x0eGetRoleRequest\"\x1f\n\x0fGetRoleResponse\x12\x0c\n\x04role\x18\x01 \x01(\t\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\x93\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xc7\x02\n\x04Raft\x12\x38\n\x0bSetIsActive\x12\x13.SetIsActiveRequest\x1a\x14.SetIsActiveResponse\x12\x38\n\x0bGetIsActive\x12\x13.GetIsActiveRequest\x1a\x14.GetIsActiveResponse\x12#\n\x04Stop\x12\x0c.StopRequest\x1a\r.StopResponse\x12,\n\x07GetRole\x12\x0f.GetRoleRequest\x1a\x10.GetRoleResponse\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETISACTIVEREQUEST']._serialized_start=14
  _globals['_SETISACTIVEREQUEST']._serialized_end=52
  _globals['_SETISACTIVERESPONSE']._serialized_start=54
  _globals['_SETISACTIVERESPONSE']._serialized_end=93
  _globals['_GETISACTIVEREQUEST']._serialized_start=95
  _globals['_GETISACTIVEREQUEST']._serialized_end=133
  _globals['_GETISACTIVERESPONSE']._serialized_start=135
  _globals['_GETISACTIVERESPONSE']._serialized_end=174
  _globals['_STOPREQUEST']._serialized_start=176
  _globals['_STOPREQUEST']._serialized_end=203
  _globals['_STOPRESPONSE']._serialized_start=205
  _globals['_STOPRESPONSE']._serialized_end=236
  _globals['_GETROLEREQUEST']._serialized_start=238
  _globals['_GETROLEREQUEST']._serialized_end=254
  _globals['_GETROLERESPONSE']._serialized_start=256
  _globals['_GETROLERESPONSE']._serialized_end=287
  _globals['_REQUESTVOTEREQUEST']._serialized_start=289
  _globals['_REQUESTVOTEREQUEST']._serialized_end=387
  _globals['_REQUESTVOTERESPONSE']._serialized_start=389
  _globals['_REQUESTVOTERESPONSE']._serialized_end=445
  _globals['_LOGENTRY']._serialized_start=447
  _globals['_LOGENTRY']._serialized_end=488
  _globals['_APPENDENTRIESREQUEST']._serialized_start=491
  _globals['_APPENDENTRIESREQUEST']._serialized_end=638
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=640
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=694
  _globals['_RAFT']._serialized_start=697
  _globals['_RAFT']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
