# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RaftManager.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'RaftManager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11RaftManager.proto\"3\n\x11SendActiveRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\"%\n\x12SendActiveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x44\n\x0bRaftManager\x12\x35\n\nSendActive\x12\x12.SendActiveRequest\x1a\x13.SendActiveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RaftManager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDACTIVEREQUEST']._serialized_start=21
  _globals['_SENDACTIVEREQUEST']._serialized_end=72
  _globals['_SENDACTIVERESPONSE']._serialized_start=74
  _globals['_SENDACTIVERESPONSE']._serialized_end=111
  _globals['_RAFTMANAGER']._serialized_start=113
  _globals['_RAFTMANAGER']._serialized_end=181
# @@protoc_insertion_point(module_scope)
