# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import RaftManager_pb2 as RaftManager__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in RaftManager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RaftManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendIsActive = channel.unary_unary(
                '/RaftManager/SendIsActive',
                request_serializer=RaftManager__pb2.IsActiveRequest.SerializeToString,
                response_deserializer=RaftManager__pb2.IsActiveResponse.FromString,
                _registered_method=True)
        self.SendRole = channel.unary_unary(
                '/RaftManager/SendRole',
                request_serializer=RaftManager__pb2.SendRoleRequest.SerializeToString,
                response_deserializer=RaftManager__pb2.SendRoleResponse.FromString,
                _registered_method=True)
        self.SendTerm = channel.unary_unary(
                '/RaftManager/SendTerm',
                request_serializer=RaftManager__pb2.SendTermRequest.SerializeToString,
                response_deserializer=RaftManager__pb2.SendTermResponse.FromString,
                _registered_method=True)


class RaftManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendIsActive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendIsActive': grpc.unary_unary_rpc_method_handler(
                    servicer.SendIsActive,
                    request_deserializer=RaftManager__pb2.IsActiveRequest.FromString,
                    response_serializer=RaftManager__pb2.IsActiveResponse.SerializeToString,
            ),
            'SendRole': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRole,
                    request_deserializer=RaftManager__pb2.SendRoleRequest.FromString,
                    response_serializer=RaftManager__pb2.SendRoleResponse.SerializeToString,
            ),
            'SendTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTerm,
                    request_deserializer=RaftManager__pb2.SendTermRequest.FromString,
                    response_serializer=RaftManager__pb2.SendTermResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RaftManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RaftManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendIsActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RaftManager/SendIsActive',
            RaftManager__pb2.IsActiveRequest.SerializeToString,
            RaftManager__pb2.IsActiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RaftManager/SendRole',
            RaftManager__pb2.SendRoleRequest.SerializeToString,
            RaftManager__pb2.SendRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RaftManager/SendTerm',
            RaftManager__pb2.SendTermRequest.SerializeToString,
            RaftManager__pb2.SendTermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
